src/Entity/Trick.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OrderBy;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Trick
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime" )
     */
    private $dateAdd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="trick")
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="tricks")
     */
    private $tag;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TrickImage", mappedBy="trickList"  , cascade={"persist", "remove"} )
     * @ORM\OrderBy({"position" = "ASC"})
     *
     */

    private $trickImages;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TrickVideo", mappedBy="trickList"  , cascade={"persist", "remove"} )
     * @ORM\OrderBy({"position" = "ASC"})
     *
     */

    private $trickVideos;

    /**
     * @ORM\Column(type="integer")
     */
    private $position;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tag = new ArrayCollection();
        $this->dateAdd = new \DateTime();
        $this->trickImages = new ArrayCollection();
        $this->trickVideos = new ArrayCollection();
    }

    public function getThumbnail()
    {
        $images = $this->trickImages->filter(function (TrickImage $image) {
            return $image->getThumbnail() == true;
        });
        return $images->first();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    private function slugify($text)
    {
        // Strip html tags
        $text = strip_tags($text);
        // Replace non letter or digits by -
        $text = preg_replace('~[^\pL\d]+~u', '-', $text);
        // Transliterate
        setlocale(LC_ALL, 'en_US.utf8');
        $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
        // Remove unwanted characters
        $text = preg_replace('~[^-\w]+~', '', $text);
        // Trim
        $text = trim($text, '-');
        // Remove duplicate -
        $text = preg_replace('~-+~', '-', $text);
        // Lowercase
        $text = strtolower($text);
        // Check if it is empty
        if (empty($text)) {
            return 'n-a';
        }
        // Return result
        return $text;
    }

    public function getDateAdd(): ?\DateTimeInterface
    {
        return $this->dateAdd;
    }

    public function setDateAdd(\DateTimeInterface $dateAdd): self
    {
        $this->dateAdd = $dateAdd;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }


    public function setSlug(string $slug): self
    {
        $this->slug = self::slugify($slug);

        return $this;
    }


    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrickList($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrickList(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTag(): Collection
    {
        return $this->tag;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tag->contains($tag)) {
            $this->tag[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tag->contains($tag)) {
            $this->tag->removeElement($tag);
        }

        return $this;
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }


    /**
     * @return Collection|TrickImage[]
     */
    public function getTrickImages(): Collection
    {
        return $this->trickImages;
    }

    public function addTrickImage(TrickImage $trickImage): self
    {
        if (!$this->trickImages->contains($trickImage)) {
            $this->trickImages[] = $trickImage;
            $trickImage->setTrickList($this);
        }

        return $this;
    }

    public function removeTrickImage(TrickImage $trickImage): self
    {

        //die("hh2");
        if ($this->trickImages->contains($trickImage)) {
            $this->trickImages->removeElement($trickImage);
            // set the owning side to null (unless already changed)
//            if ($trickImage->getTrickList() === $this) {
//                $trickImage->setTrickList(null);
//            }
        }

        return $this;
    }

    /**
     * @return Collection|TrickImage[]
     */
    public function getTrickVideos(): Collection
    {
        return $this->trickVideos;
    }

    public function addTrickVideo(TrickVideo $trickVideo): self
    {
        if (!$this->trickVideos->contains($trickVideo)) {
            $this->trickVideos[] = $trickVideo;
            $trickVideo->setTrickList($this);
        }

        return $this;
    }

    public function removeTrickVideo(TrickVideo $trickVideo): self
    {
        if ($this->trickVideos->contains($trickVideo)) {
            $this->trickVideos->removeElement($trickVideo);
            // set the owning side to null (unless already changed)
//            if ($trickVideo->getTrickList() === $this) {
//                $trickVideo->setTrickList(null);
//            }
        }

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }


}

src/Entity/TrickVideo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickVideoRepository")
 */
class TrickVideo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Trick", inversedBy="trickVideos")
     * @ORM\JoinColumn(nullable=false)

     */
    private $trickList;



    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Video" ,  inversedBy="trickVideos" )
     * @ORM\JoinColumn(name="video_list", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     */
    private $videoList;

    /**
     * @ORM\Column(type="integer")
     */
    private $position;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTrickList(): ?Trick
    {
        return $this->trickList;
    }

    public function setTrickList(?Trick $trick): self
    {
        $this->trickList = $trick;

        return $this;
    }

    public function getVideoList(): ?Video
    {
        return $this->videoList;
    }

    public function getUrl()
    {

        return $this->getVideoList()->getUrl();
    }
    public function setVideoList(?Video $video): self
    {
        $this->videoList = $video;

        return $this;
    }



    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{


    const USER_ROLES = [ 'Contributeur' => 'ROLE_USER',



        'Administrateur' => 'ROLE_ADMIN',
        'Super administrateur' => 'ROLE_SUPER_ADMIN',
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="user")
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function __construct()
    {
        $this->comments = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }



    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {

        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
      //  $roles[] = 'ROLE_SUPER_ADMIN';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Controller/TrickController.php
<?php
/**
 * Created by PhpStorm.
 * User: worf
 * Date: 08/02/19
 * Time: 21:47
 */

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\TrickImage;
use App\Form\CommentsType;
use App\Repository\TrickRepository;
use App\Repository\TrickImageRepository;
use App\Repository\TrickVideoRepository;
use Doctrine\ORM\EntityManagerInterface;
use DateTime;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use App\Entity\Trick;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Repository\TagRepository;
use App\Service\Configuration;

class TrickController extends AbstractController
{

    /**
     * @var TrickRepository
     */
    private $repository;
    private $repositoryImage;
    private $repositoryVideo;

    public function __construct(TrickRepository $repository,
                                TrickImageRepository $repositoryImage,
                                TrickVideoRepository $repositoryVideo)
    {
        $this->repository = $repository;
        $this->repositoryImage = $repositoryImage;
        $this->repositoryVideo = $repositoryVideo;

    }

    /**
     * @Route("/trick/page/{page}", name="listtrick")
     */

    public function list($page, TrickRepository $trickRepository, TagRepository $tagRepository, Configuration $configuration) // autloading
    {

        $nbrTrickHomePage = $configuration->get('NBPOSTHOME', 5);

        $first = $page * $nbrTrickHomePage;
        //$tricks = $trickRepository->findBy(array(),   array('position'=>'asc'), $nbrTrickHomePage );
        $tricks = $trickRepository->getTricks($first, $nbrTrickHomePage);
        $nbrTricks = $tricks->count();
        $tags = $tagRepository->findAll();
        return $this->render('trick/ajax.html.twig', [
            'tricks' => $tricks,
            'nbrTricks'=>$nbrTricks,
            'page'=>ceil($nbrTricks / $nbrTrickHomePage),
            'tags' => $tags
        ]);
    }

    /**
     * @Route("/trick/{slug}", name="trickSlug" )
     */

    public function index(Trick $trick, Request $request, EntityManagerInterface $em)
    {

        $comments = new Comment();
        $formComments = $this->createForm(CommentsType::class, $comments);
        $formComments->handleRequest($request);

        if ($formComments->isSubmitted() && $formComments->isValid()) {
            $user = $this->getUser();
            $comments->setTrick($trick);
            $comments->setUser($user);
            $em->persist($comments);
            $em->flush();
            $request->getSession()->getFlashBag()->add('notice', 'Commentaire bien enregistrée.');
            return $this->redirectToRoute('trickSlug', ['slug' => $trick->getSlug()]);
        }
        return $this->render('trick/index.html.twig', [
            'trick' => $trick,
            'formComments' => $formComments->createView(),
        ]);
    }
}

templates/trick/ajax.html.twig
        {% for trick in tricks %}
            <div class="col-4 col-6-medium col-12-small post">
                <div class="col-4 col-6-medium col-12-small">
                    <section class="box">
                        <a href="{{ path('trickSlug', {'slug': trick.slug}) }}" class="image featured">
                            {% if trick.thumbnail %}
                                <img src="{{ asset("uploads/trick/" ~ trick.thumbnail.path) }}" width="100%">
                            {% endif %}</a>
                        <header>
                            <h3>{{ trick.name }}</h3>
                        </header>
                        <p>{{ trick.description }}</p>
                        <footer>
                            <ul class="actions">
                                <li><a href="{{ path('trickSlug', {'slug': trick.slug}) }}" class="button alt">Voir la
                                        suite</a></li>
                            </ul>
                            <ul>
                                {% for tag in trick.tag %}
                                    <li>{{ tag.name }}</li>
                                {% endfor %}

                            </ul>
                        </footer>
                    </section>
                </div>
            </div>
        {% endfor %}

templates/trick/form.html.twig
{# templates/default/new.html.twig #}
{% macro printImageForm(imageform) %}
    <div class="col-12 js-collection-item">
            <span class="fa fa-close"></span>

            {% for choice in imageform.imageList.vars.choices %}
                 <label><img  height="100px" src="{{ asset("uploads/trick/" ~ choice.data.path) }}"/>
                <input type="radio" name="{{ imageform.imageList.vars.full_name}}"   value="{{ choice.value }}">
                 </label>
            {% endfor %}

            {{ form_errors(imageform) }}
        {{ form_row(imageform.thumbnail) }}
    </div>
{% endmacro %}
{% macro printVideoForm(videoForm) %}
    <div class="col-12 js-collection-item">
        <span class="fa fa-close"></span>

        {% for choice in videoForm.videoList.vars.choices %}
            <label>{{ choice.data.url }}
                <input type="radio" name="{{ videoForm.videoList.vars.full_name}}"   value="{{ choice.value }}">
            </label>
        {% endfor %}

        {{ form_errors(videoForm) }}
    </div>
{% endmacro %}

{% import _self as formMacros %}

{% extends "layout.html.twig" %}
{% block content %}


    <div class="col-lg-7 col-md-10 mx-auto">

        {% if trick.id %}
            <h1>Modifier le trick : {{ trick.name }}</h1>
        {% else %}
            <h1>Nouveaui trick</h1>
        {% endif %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}

        {{ form_row(form.description) }}
        {{ form_row(form.name) }}
        {{ form_row(form.description) }}
        {{ form_row(form.tag) }}


        <div id="imageform">

        <h3>Image</h3>


        <div class="row" id="imageBlock" data-prototype="{{ formMacros.printImageForm(form.trickImages.vars.prototype)|e('html_attr') }}">

            {% for image in form.trickImages %}
                <div class="js-collection-item col-12">

                        <a href="" class="js-remove-collection-item pull-right">
                            <span class="fa fa-close"></span>
                        </a>


                        <img  width="90" src="{{ asset("uploads/trick/" ~ image.imageList.vars.data.path) }}" />
                        <div style="display: none" >{{ form_row(image.imageList ) }}</div>

                        {{ form_row(image.thumbnail ) }}
                        {{ form_errors(image) }}


                </div>
            {% endfor %}
        </div>
    </div>
    <div id="videoform">

        <h3>Video</h3>
        <div class="row" id="videoBlock"  data-prototype="{{ formMacros.printVideoForm(form.trickVideos.vars.prototype)|e('html_attr') }}">

            {% for video in form.trickVideos %}
            <div class="js-collection-item col-12">

                    <a href="" class="js-remove-collection-item pull-right">
                        <span class="fa fa-close"></span>
                    </a>
                        {{ form_errors(video) }}
                    {{ video.videoList.vars.data.url}}
                    <div style="display: none" >{{ form_row(video.videoList ) }}</div>

            </div>
            {% endfor %}
        </div>
    </div>
        {{ form_row(form.Submit) }}
        {{ form_errors(form) }}
        {{ form_end(form, {'render_rest': false}) }}

    </div>
    <script>

        var $collectionHolderImg;
        var $collectionHolderVideo;
        jQuery(document).ready(function() {
            var $wrapper = $('#imageBlock');
            $wrapper.on('click', '.js-remove-collection-item', function(e) {
                e.preventDefault();
                $(this).closest('.js-collection-item')
                    .fadeOut()
                    .remove();
            });
        });
        // setup an "add a tag" link
        var $addTagButtonImg = jQuery('<button type="button" class="add_tag_link">Add a image</button>');
        var $newLinkLiImg = jQuery('<p></p>').append($addTagButtonImg);
        var $addTagButtonVideo = jQuery('<button type="button" class="add_tag_link">Add a video</button>');
        var $newLinkLiVideo = jQuery('<p></p>').append($addTagButtonVideo);


        jQuery(document).ready(function () {
            $collectionHolderImg = jQuery('#imageBlock');
            $collectionHolderImg.append($newLinkLiImg);
            $collectionHolderImg.data('index', $collectionHolderImg.find(':input').length);
            $addTagButtonImg.on('click', function (e) {
                addItemForm($collectionHolderImg, $newLinkLiImg);
            });
            $collectionHolderVideo = jQuery('#videoBlock');
            $collectionHolderVideo.append($newLinkLiVideo);
            $collectionHolderVideo.data('index', $collectionHolderVideo.find(':input').length);
            $addTagButtonVideo.on('click', function (e) {
                // add a new tag form (see next code block)
                addItemForm($collectionHolderVideo, $newLinkLiVideo);
            });
        });

        function addItemForm($collectionHolder, $newLinkLi) {
            // Get the data-prototype explained earlier
            var prototype = $collectionHolder.data('prototype');
            // get the new index
            var index = $collectionHolder.data('index');
            var newForm = prototype;
            newForm = newForm.replace(/__name__/g, index);
            $collectionHolder.data('index', index + 1);
            // Display the form in the page in an li, before the "Add a tag" link li
            var $newFormLi = $('<span></span>').append(newForm);
            $newLinkLi.before($newFormLi);
        }





    </script>

{% endblock %}


{% block javascripts %}
    <script src="{{ asset('assets/js/Sortable.js') }}"></script>

    <script>

        $(document).ready(function () {
            new Sortable(imageBlock, {
                animation: 150,
                ghostClass: 'blue-background-class',

                onSort: function (/**Event*/evt) {


                },
            });
            new Sortable(videoBlock, {
                animation: 150,
                ghostClass: 'blue-background-class',

                onSort: function (/**Event*/evt) {


                },
            });
        });
    </script>

{% endblock %}

templates/trick/index.html.twig
{% extends "layout.html.twig" %}
{% block content %}

    <section class="nopadding col-lg-12 mx-auto text-center border border-dark">


        <header class="masthead content" id="front_picture" style="
                {% if trick.thumbnail %}background-image:        url('{{ asset("uploads/trick/" ~ trick.thumbnail.path) }}');{% endif %}">

            {% if app.user %}
                <div class="fai">
                    <a href="{{ path('edittrick', {'id': trick.id}) }}"><i class="fa fa-pencil cursor"></i></a>
                    <a href="{{ path('deletetrick', {'id': trick.id}) }}" data-toggle="modal"
                       data-target="#confirm-delete"> <i class="fa fa-trash cursor"></i></a>
                </div>
            {% endif %}


            <div class="intro-text">

                <div class="intro-heading col-lg-4 mx-auto text-center">
                    {{ trick.name }}
                </div>

            </div>
        </header>

        <div class="d-sm-none mx-auto">
            <button type="button" class="btn btn-dark mt-3">See Medias</button>
        </div>

        <div class="d-none d-sm-block">


            <div class="album py-5 bg">
                <div class="container">
                    <div class="row">

                        {% for image in trick.trickImages %}

                            <div class="col-md-2" id="">
                                <div class="card mb-4 box-shadow">
                                    <img class="card-img-top" src="{{ asset("uploads/trick_min/" ~ image.imageList.path) }}"
                                         alt="none" >
                                </div>
                            </div>



                        {% endfor %}



                        {% for video in trick.trickVideos %}
                            <div class="col-md-2" id="">


                                    <div class="card mb-4 box-shadow">



                                        <div class="embed-responsive embed-responsive-4by3">

                                        <iframe class="embed-responsive-item" src="{{ video.videolist.url }}"
                                                frameborder="0" allow="autoplay; encrypted-media"
                                                allowfullscreen=""></iframe>
                                        </div>
                                    </div>


                            </div>
                        {% endfor %}

                    </div>
                </div>




            </div>


            <div class="col-lg-10 mx-auto mt-5 mb-5">
                <p class="text-justify">
                    {{ trick.description | raw }}


                </p>
            </div>


            <hr class="col-lg-10">


            <div class="row text-center">
                {% if app.user %}
                    <div class="col-sm-10 col-md-8 mx-auto">
                        {{ form_start(formComments) }}
                        {{ form_row(formComments.description) }}
                        {{ form_row(formComments.description) }}
                        <button type="submit" class="btn btn-success col-sm-s8 mx-auto">Laisser un commentaire</button>
                        {{ form_end(formComments) }}
                    </div>
                {% else %}
                    <div class="col-sm-10 col-md-8 mx-auto">
                        <h3>Veuillez vous connecter pour laisser un commentaire</h3>
                        <p class="p_center"><a class="italic" href="{{ path('login') }}">Connectez-vous</a>
                            {#ou <a class="italic" href="{{path('register')}}">créez un compte</a>#}

                    </div>
                {% endif %}
            </div>

            <hr>

            {% if trick.comments  | length == 0 %}
                <h4 class="p_center">Aucun commentaire pour ce Trick. Soyez le premier à commenter.</h4>
            {% elseif  trick.comments | length == 1 %}
                <i class="far fa-comments"></i> {{ trick.comments  | length }} Commentaire
            {% else %}
                <i class="far fa-comments"></i> {{ trick.comments  | length }} Commentaires
            {% endif %}

            <section id="comments">

                <aside>
                    <div class="container" id="comments-data">

                        {% for comment in trick.comments %}


                            <div class="row listComments">
                                <div class="col-lg-7 mx-auto mb-3 mt-2">
                                    <div class="panel panel-white post panel-shadow">
                                        <div class="post-heading">
                                            <div class="pull-left image">
                                            <img src="{{ asset("uploads/trick_min/" ~  comment.user.avatar) }}" class="img-circle avatar" alt="user profile image">

                                            </div>
                                            <div class="text-left meta">

                                                <div class="title">
                                                    <p><b>{{ comment.user.username }}</b> <i
                                                                class="text-muted time">({{ comment.dateAdd | date('d/m/Y à H:i') }}
                                                            )</i></p>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="post-description text-justify">
                                            <p>{{ comment.description }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}


                    </div>

                </aside>

            </section>

    </section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}